* GBNF Mode for GNU Emacs

[[https://www.gnu.org/licenses/gpl-3.0.txt][https://img.shields.io/badge/license-GPL_3-green.svg]]

A GNU Emacs major mode for editing GBNF grammars.

#+begin_quote
“Precise language is not the problem.  Clear language is the problem.”

Richard Feynman
#+end_quote

Currently provides basic syntax and font-locking for GBNF files. GBNF (GGML BNF) is the format used to define formal grammars that can be used to constrain model outputs in [[https://github.com/ggerganov/llama.cpp][llama.cpp]]. For details, see [[https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md][the llama.cpp documentation on "grammars"]].

This package is a fork of [[https://github.com/sergeyklay/bnf-mode][sergeyklay/bnf-mode: A GNU Emacs major mode for editing BNF grammars]], originally developed by Serghei Iakovlev. 

When developing this mode, the following documents were taken into account:

- [[https://www.masswerk.at/algol60/report.htm][Revised Report on the Algorithmic Language Algol 60]]
- [[https://tools.ietf.org/html/rfc822][RFC822]]: Standard for ARPA Internet Text Messages
- [[https://tools.ietf.org/html/rfc5234][RFC5234]]: Augmented GBNF for Syntax Specifications: AGBNF
- [[https://tools.ietf.org/html/rfc7405][RFC7405]]: Case-Sensitive String Support in AGBNF
- [[https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md][llama.cpp's grammar documentation]]

** Features

- Basic syntax definition
- Syntax highlighting

** Installation

Known to work with GNU Emacs 25.1 and later.  GBNF Mode may work with
older versions of Emacs, or with other flavors of Emacs (e.g. XEmacs)
but this is /not/ guaranteed.  Bug reports for problems related to using
GBNF Mode with older versions of Emacs will most like not be addressed.

The master of all the material is the Git repository at
https://github.com/oblivia-simplex/gbnf-mode .

NOTE: The ~master~ branch will always contain the latest unstable version.
If you wish to check older versions or formal, tagged release, please switch
to the relevant [[https://github.com/sergeyklay/gbnf-mode/tags][tag]].

The recommended way to install this package is to use [[https://github.com/radian-software/straight.el][straight.el]], like so:

#+begin_src emacs-lisp
  (use-package gbnf-mode
    :straight (gbnf-mode
  	     :type git
  	     :host github
  	     :repo "oblivia-simplex/gbnf-mode")
    :config (lambda ()
  	    (add-to-list 'auto-mode-alist
  			 '("\\.gbnf\\'" . gbnf-mode))))
#+end_src

To learn on how to use any other installation methods refer to relevant
documentation.

** Usage

*** Interactive Commands

| Command (For the ~M-x~ prompt.) | Description                      |
|---------------------------------+----------------------------------|
| ~gbnf-mode~                      | Switches to GBNF Mode.            |

By default any file that matches the glob ~*.gbnf~ is automatically opened
in ~gbnf-mode~.

** Customization

To customize various options, use command as follows:

#+begin_src
M-x customize-group RET gbnf RET
#+end_src

** External Links

- [[https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form][Wikipedia: Backus–Naur form]]
- [[https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_form][Wikipedia: Extended Backus–Naur form]]
- [[https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_form][Wikipedia: Augmented Backus–Naur form]]
- [[https://www.cl.cam.ac.uk/~mgk25/iso-14977.pdf][ISO/IEC 14977: EGBNF]]
- [[https://www.ics.uci.edu/~pattis/ICS-33/lectures/egbnf.pdf][EGBNF: A Notation to Describe Syntax]]

** License

GBNF Mode is open source software licensed under the [[https://github.com/sergeyklay/gbnf-mode/blob/master/LICENSE][GNU General Public Licence version 3]].
Copyright © 2019, 2020, 2021, 2022 Free Software Foundation, Inc.

*** Note On Copyright Years

In copyright notices where the copyright holder is the Free Software Foundation,
then where a range of years appears, this is an inclusive range that applies to
every year in the range.  For example: 2005-2008 represents the years 2005,
2006, 2007, and 2008.
